channels:
  - defaults

dependencies:
  - numpy>=1.20
  - pip>=20.3.3
  - python=3.9
  - pip:
      - matplotlib>=3.3.3
      - jupyter
      - notebook
      - jupytext
      - -e ../../
      - scipy>=1.7
      - pymc3>=3.11
      - pymc3_ext
      - corner
      - arviz
