[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel"]
build-backend = 'setuptools.build_meta'

[tool.jupytext]
formats = "light,ipynb"
formats = "notebooks///ipynb,src/figures///light"
